v-change-wordpress-admin-passwords: improve error handling

diff --git a/bin/v-change-wordpress-admin-passwords b/bin/v-change-wordpress-admin-passwords
--- a/bin/v-change-wordpress-admin-passwords
+++ b/bin/v-change-wordpress-admin-passwords
@@ -30,14 +30,6 @@ else
     WP_RUN="/usr/local/vesta/bin/v-run-wp-cli $DOMAIN --skip-plugins --skip-themes"
 fi
 
-return_code=$?
-
-if [ $return_code -ne 0 ]; then
-    echo "WP-CLI error:"
-    cat /home/$USER/web/$DOMAIN/wp-cli-error.log
-    exit $return_code
-fi
-
 # random 10-char password
 gen_pass() { tr -dc 'A-Za-z0-9' </dev/urandom | head -c 10; }
 
@@ -54,8 +46,19 @@ if [ -f /home/$USER/web/$DOMAIN/wp-admin-password-change.txt ]; then
     rm /home/$USER/web/$DOMAIN/wp-admin-password-change.txt
 fi
 
-RUN="$WP_RUN user list --role=administrator --fields=ID,user_login,user_email --format=csv --skip-plugins --skip-themes 2>/dev/null | tail -n +2"
+RUN="$WP_RUN user list --role=administrator --fields=ID,user_login,user_email --format=csv --skip-plugins --skip-themes"
 ADMIN_LIST_CSV=$(eval "$RUN")
+
+return_code=$?
+
+if [ $return_code -ne 0 ]; then
+    echo "WP-CLI error:"
+    echo "return code: $return_code"
+    cat /home/$USER/web/$DOMAIN/wp-cli-error.log
+    exit $return_code
+fi
+
+ADMIN_LIST_CSV=$(echo "$ADMIN_LIST_CSV" | tail -n +2)
 
 [ -z "$ADMIN_LIST_CSV" ] && { echo "No administrator accounts found."; exit 0; }
 
