Replace direct calls to 'wp' with 'v-run-wp-cli'

diff --git a/bin/v-install-wordpress b/bin/v-install-wordpress
--- a/bin/v-install-wordpress
+++ b/bin/v-install-wordpress
@@ -71,12 +71,12 @@ if [ -z "$email" ]; then
 fi
 
 if [ ! -d "/home/$user" ]; then
-    echo "User doesn't exist";
+    echo "= Error: Folder /home/$user doesn't exist";
     exit 1;
 fi
 
 if [ ! -d "/home/$user/web/$domain/public_html" ]; then
-    echo "Domain doesn't exist";
+    echo "= Error: Folder /home/$user/web/$domain/public_html doesn't exist";
     exit 1;
 fi
 
@@ -138,24 +138,35 @@ fi
 
 /usr/local/vesta/bin/v-add-database "$user" "$DBUSERSUF" "$DBUSERSUF" "$PASSWDDB" "mysql"
 
-if [ ! -f "/usr/local/bin/wp" ]; then
-    echo "=== Downloading latest wp-cli"
-    wget -nv https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp
-    chmod +x /usr/local/bin/wp
+if [ ! -f "/usr/local/bin/wp" ] || [ ! -f "/usr/local/bin/wp-cli/php/boot-fs.php" ]; then
+    echo "= WP CLI is not installed. Installing..."
+    /usr/local/vesta/bin/v-install-wp-cli
+fi
+if [ ! -f "/usr/local/bin/wp" ] && [ ! -f "/usr/local/bin/wp-cli/php/boot-fs.php" ]; then
+    exit 1;
 fi
 
 WORKINGDIR="/home/$user/web/$domain/public_html"
 rm -rf $WORKINGDIR/*
 cd $WORKINGDIR
 
-sudo -H -u$user wp core download
-sudo -H -u$user wp core config --dbname=$DBUSER --dbuser=$DBUSER --dbpass=$PASSWDDB
+/usr/local/vesta/bin/v-run-wp-cli $domain core download
+if [ ! -f "$WORKINGDIR/index.php" ]; then
+    echo "= WordPress installation failed: WordPress core download failed."
+    exit 1;
+fi
+
+/usr/local/vesta/bin/v-run-wp-cli $domain core config --dbname=$DBUSER --dbuser=$DBUSER --dbpass=$PASSWDDB
+if [ ! -f "$WORKINGDIR/wp-config.php" ]; then
+    echo "= WordPress installation failed: WordPress core config failed, wp-config.php not found."
+    exit 1;
+fi
 
 password=$(LC_CTYPE=C tr -dc A-Za-z0-9_\!\@\#\$\%\^\&\*\(\)-+= < /dev/urandom | head -c 12)
 
 wpadmin=$(echo "$domain" | sed 's#\.#_#g')_4dm1n
 
-sudo -H -u$user wp core install --url="$domain" --title="$domain" --admin_user="$wpadmin" --admin_password="$password" --admin_email="$email" --path=$WORKINGDIR
+/usr/local/vesta/bin/v-run-wp-cli $domain core install --url="$domain" --title="$domain" --admin_user="$wpadmin" --admin_password="$password" --admin_email="$email" --path=$WORKINGDIR
 
 mysql -u$DBUSER -p$PASSWDDB -e "USE $DBUSER; update wp_options set option_value = '$PROTOCOL://$domain' where option_name = 'siteurl'; update wp_options set option_value = '$PROTOCOL://$domain' where option_name = 'home';"
 
diff --git a/bin/v-install-wp-cli b/bin/v-install-wp-cli
--- a/bin/v-install-wp-cli
+++ b/bin/v-install-wp-cli
@@ -24,9 +24,15 @@ if [ ! -f "/usr/local/bin/composer" ]; then
 fi
 
 if [ -d "/usr/local/bin/wp-cli" ]; then
-    echo "= Removing old WP CLI..."
+    echo "= Removing old myVesta WP CLI..."
     rm -rf /usr/local/bin/wp-cli
 fi
+
+echo "= Installing classic WP CLI..."
+wget -nv https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O /usr/local/bin/wp
+chmod +x /usr/local/bin/wp
+
+echo "= Installing myVesta WP CLI..."
 
 cd /usr/local/bin
 git clone https://github.com/wp-cli/wp-cli.git
@@ -36,9 +42,21 @@ chown -R www-data:www-data wp-cli
 cd wp-cli/
 sudo -H -u www-data composer install
 
+echo "= Installing search-replace-command package..."
+sudo -H -u www-data WP_CLI_PACKAGES_DIR=/usr/local/bin/wp-cli/packages php /usr/local/bin/wp-cli/php/boot-fs.php package install wp-cli/search-replace-command
+
 # Fix terminal columns issue for WP CLI
+echo "= Fixing terminal columns issue for WP CLI..."
 /usr/local/vesta/bin/v-sed '$columns = 80;' "if (file_exists('/usr/local/bin/wp-cli/COLUMNS')) \$columns=intval(file_get_contents('/usr/local/bin/wp-cli/COLUMNS')); else \$columns = 80;" '/usr/local/bin/wp-cli/vendor/wp-cli/php-cli-tools/lib/cli/Shell.php'
 
-echo "= WP CLI installed successfully."
+echo ""
 
-exit 0;
+if [ -f "/usr/local/bin/wp-cli/php/boot-fs.php" ] || [ -f "/usr/local/bin/wp" ]; then
+    echo "= WP CLI installed successfully."
+    echo "= Usage: v-run-wp-cli DOMAIN WP_CLI_COMMAND"
+    exit 0;
+else
+    echo "= WP CLI installation failed."
+    echo "= Please install it manually."
+    exit 1;
+fi
