Adding myVesta rules to SpamAssassin

diff --git a/src/deb/vesta/postinst b/src/deb/vesta/postinst
--- a/src/deb/vesta/postinst
+++ b/src/deb/vesta/postinst
@@ -25,6 +25,41 @@ fi
 echo "1" > /usr/local/vesta/data/upgrades/show_changelog
 chmod a=rw /usr/local/vesta/data/upgrades/show_changelog
 
+# Adding myVesta rules to SpamAssassin
+if [ -d "/etc/spamassassin" ]; then
+    spamassassin_modified=0
+    if [ ! -f "/etc/spamassassin/myvesta.cf" ]; then
+        touch /etc/spamassassin/myvesta.cf
+    fi
+    if ! grep -q 'RCVD_IN_RP_SAFE' /etc/spamassassin/myvesta.cf; then
+        echo "== Adding RCVD_IN_RP_ myVesta rules to SpamAssassin"
+        echo 'score RCVD_IN_RP_SAFE 0' >> /etc/spamassassin/myvesta.cf
+        echo 'score RCVD_IN_RP_CERTIFIED 0' >> /etc/spamassassin/myvesta.cf
+        spamassassin_modified=1
+    fi
+    if ! grep -q 'SPF_FAIL' /etc/spamassassin/myvesta.cf; then
+        echo "== Adding SPF_FAIL myVesta rules to SpamAssassin"
+    cat <<EOF >> /etc/spamassassin/myvesta.cf
+score SPF_FAIL 3.0
+score SPF_SOFTFAIL 4.0
+score SPF_NONE 4.0
+EOF
+        spamassassin_modified=1
+    fi
+
+    if [ $spamassassin_modified -eq 1 ]; then
+        spamassassin_running=$(/usr/local/vesta/bin/v-list-sys-services | grep 'spamassassin\|spamd' | grep -c 'running')
+        if [ $spamassassin_running -eq 1 ]; then
+            echo "== Restarting SpamAssassin"
+            if [ "$release" -lt 12 ]; then
+                    systemctl restart spamassassin.service
+                else
+                    systemctl restart spamd.service
+            fi
+        fi
+    fi
+fi
+
 # Adding ProFTPD to Fail2Ban
 if [ -f "/etc/fail2ban/jail.local" ] && [ -f "/etc/proftpd/proftpd.conf" ]; then
     if ! grep -q 'proftpd' /etc/fail2ban/jail.local; then
@@ -122,14 +157,18 @@ fi
 # Adding Barracuda RBL to SpamAssassin
 if [ ! -f "/usr/local/vesta/data/upgrades/barracuda_rbl" ]; then
     spamassassin_installed=$(/usr/local/vesta/bin/v-list-sys-services | grep -c 'spamassassin')
-    spamassassin_running=$(/usr/local/vesta/bin/v-list-sys-services | grep 'spamassassin' | grep -c 'running')
+    spamassassin_running=$(/usr/local/vesta/bin/v-list-sys-services | grep 'spamassassin\|spamd' | grep -c 'running')
     if [ $spamassassin_installed -eq 1 ]; then
         echo "== Adding Barracuda RBL to SpamAssassin"
         wget -nv -O /etc/spamassassin/barracuda.cf http://c.myvestacp.com/tools/spamassassin/barracuda.cf
     fi
     if [ $spamassassin_running -eq 1 ]; then
         echo "== Restarting SpamAssassin"
-        systemctl restart spamassassin
+        if [ "$release" -lt 12 ]; then
+            systemctl restart spamassassin.service
+        else
+            systemctl restart spamd.service
+        fi
     fi
     touch /usr/local/vesta/data/upgrades/barracuda_rbl
 fi
